# Copyright 2024 DeepMind Technologies Limited
#
# AlphaFold 3 source code is licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# To request access to the AlphaFold 3 model parameters, follow the process set
# out at https://github.com/google-deepmind/alphafold3. You may only use these
# if received directly from Google. Use is subject to terms of use available at
# https://github.com/google-deepmind/alphafold3/blob/main/WEIGHTS_TERMS_OF_USE.md

from alphafold3.cpp import cif_dict

class MmcifLayout:
  def atom_range(self, residue_index: int) -> tuple[int, int]: ...
  def chain_starts(self) -> list[int]: ...
  def chains(self) -> list[int]: ...
  def model_offset(self) -> int: ...
  def num_atoms(self) -> int: ...
  def num_chains(self) -> int: ...
  def num_models(self) -> int: ...
  def num_residues(self) -> int: ...
  def residue_range(self, chain_index: int) -> tuple[int, int]: ...
  def residue_starts(self) -> list[int]: ...
  def residues(self) -> list[int]: ...

def from_mmcif(mmcif: cif_dict.CifDict, model_id: str = ...) -> MmcifLayout: ...
