wandb:
  no_wandb: false
  project: "ligand_seq_des"
  wandb_id: "zhkim216"
  group: "training"
  run_id: null
  resume: never

out_dir: "/scratch/users/zhkim216/out_dir"
exp_name: null

overfit: -1
cuda: true
num_workers: 8

finetuning:
  enabled: false
  ckpt_path: null

train:
  seed: 0
  batch_size: 8
  debug: false
  compile:
    compile_model: true
    compile_backend: inductor
    mode: "default"
    fullgraph: false
    dynamic: false

trainer:
  strategy: ddp_find_unused_parameters_true
  max_epochs: -1
  max_steps: 200000
  accumulate_grad_batches: 4
  detect_anomaly: false
  gradient_clip_val: 0.0
  precision: "bf16-mixed"
  check_val_every_n_epoch: 2
  num_sanity_val_steps: 0
  limit_val_batches: 1.0
  enable_progress_bar: false

resume:
  ckpt_path: null
  use_current_cfg: true
  overrides: {}

defaults:
  - _self_
  - denoiser: elix_mpnn
  - mask_selector: mask_selector
  - data: elix

model:
  task: "lc_seq_des"
  eps: 1.0e-8
  inf: 1.0e9
  denoiser: ${denoiser}
  mask_selector: ${mask_selector}
  ema:
    use_phema: false
    ema_decay: 0.99

mask_selector:
  name: mask_selector
  restype_masking_schedule: "uniform_cosine_t"
  atom_masking_schedule: "uniform_t"
  masking_cfg:
    constant_t:
      t: 0.0
    uniform_t:
      t_min: 0.0
      t_max: 1.0
    uniform_squared_t:
      t_min: 0.0
      t_max: 1.0
    uniform_cubed_t:
      t_min: 0.0
      t_max: 1.0
    uniform_cosine_t:
      t_min: 0.0
      t_max: 1.0
    uniform_sqrt_t:
      t_min: 0.0
      t_max: 1.0
    uniform_cbrt_t:
      t_min: 0.0
      t_max: 1.0
  scn_context_ratio: 0.02
  pseudo_ligand_backbone_mask_radius: 0
  restype_masking_cfg: ${.masking_cfg}
  atom_masking_cfg: ${.masking_cfg}


eval:
  eval_timesteps: [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  scn_context_ratio: 0.0

loss:
  task: ${model.task}
  inf: ${model.inf}
  loss_weights:
    seq_loss: 1.0
    potts_composite_loss: 1.0
    potts_composite_loss_msa: 0.0
    sidechain_chi_loss: 0.0
    sidechain_chi_offset_loss: 0.0
  seq_loss:
    label_smoothing: 0.1
    per_token_avg: false
  potts:
    label_smoothing: 0.1
    per_token_avg: false
    compile_msa_loss: false
  main_seq_loss_pocket_only: false
  main_potts_loss_pocket_only: false

optim:
  optimizer: "noam"
  adamw:
    lr: 1.0e-4
    warmup_steps: 1000
  noam:
    factor: 2
    warmup_steps: 4000
  adam_inv_sqrt:
    ref_lr: 1.0e-3
    ref_steps: 50000
    warmup_steps: 4000

logging:
  log_dir: ${out_dir}
  log_every_n_steps: 100
  wandb_watch_freq: 500
  wandb_watch_enabled: false
  wandb_watch_mode: "gradients"

checkpointing:
  save_latest_every_n_steps: 2500
  save_for_resuming_every_n_epochs: 10
  save_phema_every_n_steps: 3000

hydra:
  run:
    dir: /scratch/users/zhkim216/hydra_outputs/train_seq_denoiser/elix/${exp_name}
