defaults:
  - run_elix
  - _self_

two_stage:
  enabled: true
  direction: ps
  pocket_distance: 5.0
  use_calpha_for_pocket_annotation: false
  pocket:
    label: pocket
    model_cfg:
      model_name: "elix_mpnn"
      denoiser_train_dir: null
      ckpt_cfg:
        start_step: null
        end_step: null
        eval_every_n_ckpts: 1
        eval_last_ckpt: false
        use_ema: true
    sampling_cfg:
      base_cfg_path: ${sampling_cfg.base_cfg_path}
      overrides: ${sampling_cfg.overrides}
      guidance: ${sampling_cfg.guidance}
  scaffold:
    label: scaffold
    model_cfg:
      model_name: "elix_mpnn"
      denoiser_train_dir: null
      ckpt_cfg:
        start_step: null
        end_step: null
        eval_every_n_ckpts: 1
        eval_last_ckpt: false
        use_ema: true
    sampling_cfg:
      base_cfg_path: ${sampling_cfg.base_cfg_path}
      overrides: ${sampling_cfg.overrides}
      guidance: ${sampling_cfg.guidance}
