pdb_path: /scratch/users/zhkim216/datasets/atomworks_pdb_full_v3
parquet_path: /scratch/users/zhkim216/datasets/atomworks_pdb_full_v3/metadata.parquet
output_parquet: null
exclude_chain_types: ["CYCLIC-PSEUDO-PEPTIDE", "OTHER", "PEPTIDE NUCLEIC ACID", "POLYPEPTIDE(D)"]
seq_id_threshold: 0.3 #! LMPNN: 0.3
reuse_existing_protein_cluster_labels: false
reuse_existing_protein_cluster_ids: false # Deprecated alias for older overrides.
