pdb_path: /scratch/users/zhkim216/datasets/atomworks_pdb_full_v10
parquet_path: /scratch/users/zhkim216/datasets/atomworks_pdb_full_v10/metadata.parquet
exclude_chain_types: ["CYCLIC-PSEUDO-PEPTIDE", "OTHER", "PEPTIDE NUCLEIC ACID", "POLYPEPTIDE(D)"]
seq_id_threshold: 0.3
